### ISSUE TITLE
Lack of lws_poisoner.py

### ISSUE THREAD

**Issue by fenffef** [thunlp/OpenBackdoor#1]
The provided code is missing the lws_poisoner.py file, will it be provided later?

**Comment by Yangyi-Chen** [comment]
Hi, Xuan

Thanks for your watch on our repo. The LWS attack is a little bit special, compared to other data poisoning-based backdoor attacks. It generates poisoned data in a dynamic way. In each round, it needs to interact with the local victim model. 

So, for implementation, we don't include a specific lws_poisoner.py file, you may use the default/badnets poisoner. Please see the configs/lws_config.json file.

**Comment by fenffef** [comment]
Thanks for your reply！
