### ISSUE TITLE
syntatic conversion slow...

### ISSUE THREAD

**Issue by clearloveclearlove** [thunlp/OpenBackdoor#10]
Hi， I found that it takes about 90 hours to do syntatic attack in agnew (my device is 3090), is there any way to speed it up? Like batch syntatic conversion. :)

![image](https://user-images.githubusercontent.com/66940934/203517661-7dd6e7a5-1df5-4e9d-8cee-7732456afd63.png)

**Comment by lifan-yuan** [comment]
The syntactic poisoner relies on the SCPNAttacker implemented by OpenAttack, which does not support batch transformation. To speed up, you can manually split the dataset into small subsets and poison them in different programs.

**Comment by clearloveclearlove** [comment]
> 
Thanks :)
