### ISSUE TITLE
The files for StyleAttack are not found

### ISSUE THREAD

**Issue by XvHaidong** [thunlp/OpenBackdoor#12]
Sorry, the files in  the path 'openbackdoor/attackers/poisoners/utils/style/download.sh' are not found now. It seems that the files in those urls (tsinghua cloud) are removed. Could you please provide these files? Thanks a lot! @fuzihaofzh @zibuyu @Mrlyk423 @Yu-Shi

**Comment by cgq15** [comment]
Hi we are recovering the files. For now, you can download them from Google Drive: https://drive.google.com/drive/folders/1ApW4J3oT5N48BH_JOPc6z16nW8dy0I7N

**Comment by XvHaidong** [comment]
Thank you so much!
