### ISSUE TITLE
Cannot download data

### ISSUE THREAD

**Issue by WencongY** [thunlp/OpenBackdoor#13]
Dear authors,

I was running `python demo_attack.py --config_path ./configs/style_config.json` but the styled texts could not be found. I saw the following errors after connecting to your cloud database:

`--2023-03-02 17:26:07--  https://cloud.tsinghua.edu.cn/d/4fa2782123cc463384be/files/?p=%2Fbible.zip&dl=1
Resolving cloud.tsinghua.edu.cn (cloud.tsinghua.edu.cn)... 166.111.6.101, 2402:f000:1:406:166:111:6:101
Connecting to cloud.tsinghua.edu.cn (cloud.tsinghua.edu.cn)|166.111.6.101|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-03-02 17:26:08 ERROR 404: Not Found.

unzip:  cannot find or open index.html?p=%2Fbible.zip&dl=1, index.html?p=%2Fbible.zip&dl=1.zip or index.html?p=%2Fbible.zip&dl=1.ZIP.

No zipfiles found.
rm: cannot remove ‘index.html?p=%2Fbible.zip&dl=1’: No such file or directory
`

Would you please verify whether the data were correctly saved on your cloud and the links are valid?

Thank you,
Wencong

**Comment by lifan-yuan** [comment]
See issue https://github.com/thunlp/OpenBackdoor/issues/12
