### ISSUE TITLE
Error when performing syntax transformation

### ISSUE THREAD

**Issue by qinliu9** [thunlp/OpenBackdoor#15]
Hi, I was trying to run syntactic attack but encountered an error.

The SCPN attacker can be loaded:

<img width="1423" alt="截屏2023-03-21 上午12 22 06" src="https://user-images.githubusercontent.com/29172204/226540628-188c2a92-77fd-41cc-aa9f-aeac86e0dddc.png">

but the attack fails:

<img width="1422" alt="截屏2023-03-21 上午12 23 40" src="https://user-images.githubusercontent.com/29172204/226540895-86c2b96b-4883-4203-8e54-8c37ce655b03.png">

It would be appreciated a lot if you might help me with this error. Thanks in advance.

**Comment by lifan-yuan** [comment]
Hi, I cannot reproduce the bug, could you provide more details?

**Comment by qinliu9** [comment]
Hi, thank you for your time. I've figured it out, and it works now. Thanks again!

**Comment by WencongY** [comment]
Hello @qinliu9,

Can you pls advise how you resolved this issue? I'm facing the same error. 

Thank you!

**Comment by qinliu9** [comment]
Hi Wencong,

You might update your version of OpenAttack, since the syntactic poisoner
is based on it. Hope this helps.

Thank you!

Best,
Qin
