### ISSUE TITLE
Errors in README.md

### ISSUE THREAD

**Issue by acphile** [thunlp/OpenBackdoor#2]
Hi, 
Thank you for your nice work. I find the code in README.md is not correct. For load_dataset function (https://github.com/thunlp/OpenBackdoor/blame/main/README.md#L82)
```
poison_dataset = load_dataset({"name": "sst-2"}) 
```
I think it should be 
```
poison_dataset = load_dataset(name="sst-2") 
```
And similarly for the rest cases in README.md

Beside, for Defender part in the demo, 
```
victim = attacker.attack(victim, poison_dataset, defender)
```
However, the third argument position should be config, not defender

**Comment by lifan-yuan** [comment]
Thank you for pointing that out! We will correct these errors and double-check the docs :)
