### ISSUE TITLE
StyleAttack missing training_args.bin

### ISSUE THREAD

**Issue by courtlandvandam** [thunlp/OpenBackdoor#22]
When running stylebkd, I get the following error:

FileNotFoundError: [Errno 2] No such file or directory: 'data/transfer/bible/training_args.bin'

I tried going to OpenBackdoor github and StyleAttack github and could not find this file.

**Comment by lifan-yuan** [comment]
Hello, are you using the latest version? Previously, StyleBkdPoisoner would automatically download weights and load them from `data/transfer/bible/training_args.bin`, but now we've updated the code to directly load weights from the huggingface hub.
