### ISSUE TITLE
Error occurs when installing the environment, what the versions of python、tensorflow and torch? could you please give more details? Thank you very much!

### ISSUE THREAD

**Issue by LeiyanGithub** [thunlp/OpenBackdoor#4]
<img width="790" alt="image" src="https://user-images.githubusercontent.com/45895439/200176073-59698675-35bc-4a75-a94a-36be35b271ab.png">

**Comment by lifan-yuan** [comment]
Hi, thank you for your attention to our project.
I have checked the installation again and successfully installed the environment following the README. So, you may try to manually uninstall the existing _aiohttp_ module to solve the problem. 
And as a reference, I can run the repo with the following environment:
- Python version: 3.8.13
- transformers version: 4.19.2
- PyTorch version: 1.10.1+cu111
