### ISSUE TITLE
Unclear definition for poisoner_data_path

### ISSUE THREAD

**Issue by acphile** [thunlp/OpenBackdoor#5]
Currently in the poisoner, there exists two paths:
https://github.com/thunlp/OpenBackdoor/blob/58dcbdc1d0c81188ddb536d13683a6dcbf742416/openbackdoor/attackers/poisoners/poisoner.py#L23-L24

According to the docstring, `poison_data_basepath` is for loading and `poisoned_data_path` is for saving.

However, in the following code, we can find that both `poison_data_basepath` and `poisoned_data_path`are both used for saving, which could lead to confusion.

https://github.com/thunlp/OpenBackdoor/blob/58dcbdc1d0c81188ddb536d13683a6dcbf742416/openbackdoor/attackers/poisoners/poisoner.py#L80-L85

I suggest these two parameters can be merged as one

**Comment by lifan-yuan** [comment]
Hi, thank you for your feedback!
We set two separate parameters to distinguish between the path of a fully poisoned dataset and that of a partially poisoned dataset. To improve reusability, we first poison the entire clean dataset and save the results to `poison_data_basepath`. This poison dataset can be used to produce different partially poisoned datasets with different `poison_setting` and `poison_rate`, which are saved to `poisoned_data_path`.
However, we will consider merging them if they lead to confusion.

**Comment by acphile** [comment]
I understand. Thanks!
