### ISSUE TITLE
Issues about BKIDefender

### ISSUE THREAD

**Issue by acphile** [thunlp/OpenBackdoor#6]
I have several questions regarding to the implementation of BKIDefender
First, according to the docstring, it should have a parameter called `threshold`
https://github.com/thunlp/OpenBackdoor/blob/58dcbdc1d0c81188ddb536d13683a6dcbf742416/openbackdoor/defenders/bki_defender.py#L19
But in fact, no argument needs to be passed according to the definition.

Second, the BKIDefender would never work according to the current logic.
We know that BKIDefender requires a backdoored model to filter the training data, as also reflected in https://github.com/thunlp/OpenBackdoor/blob/58dcbdc1d0c81188ddb536d13683a6dcbf742416/openbackdoor/defenders/bki_defender.py#L32-L44
However, according to the logic of the `Attacker`, it would not pass the victim model to the defender:
https://github.com/thunlp/OpenBackdoor/blob/58dcbdc1d0c81188ddb536d13683a6dcbf742416/openbackdoor/attackers/attacker.py#L58-L60

And similar to CUBEDefender, BKIDefender should set `pre=True` but the code does not do that.

In this case, I suggest that the implementation for CUBEDefender and BKIDefender  should be unified. 
For example, for their `correct` method, they should receive an argument for the backdoored model (and also `Attacker.attack` should have an additional backdoored model argument apart from `victim` ) instead of using an inside trainer and victim model for the defender

**Comment by lifan-yuan** [comment]
Thank you for pointing this out!
It was indeed a bug, and it's fixed now.

**Comment by acphile** [comment]
https://github.com/thunlp/OpenBackdoor/blob/18a65d701f5c50d619bacb8d02076b78b0a6e1df/openbackdoor/defenders/bki_defender.py#L45

You forget to import `PLMVictim` in this file
