### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by clearloveclearlove** [thunlp/OpenBackdoor#9]
When I perform a style attack on the offenseval dataset, I find that the poisoned samples are formatted cleanly, but the offenseval original dataset has a large number of @USER symbols, which I think is unreasonable. In this case, there is a high probability that it is not the style of the text that is acting as a trigger, but rather that the poisoned samples do not have the @USER symbols.
So I suggest whether offenseval should be preprocessed before the experiment, for example filtering out the @USER symbols.
Other spam and toxic datasets have similar problems.

![1cb48c402f785bf90c6aa2d28584495](https://user-images.githubusercontent.com/66940934/201097877-49faca91-e244-4fb7-80d6-b589d78a4155.jpg)

![image](https://user-images.githubusercontent.com/66940934/201097949-ea7eda31-30bd-4601-867a-e665f3dbce46.png)

**Comment by lifan-yuan** [comment]
Thanks for your suggestion. We have updated the toxic datasets with the pre-processed ones.

**Comment by clearloveclearlove** [comment]
Thank you for your reply, how can I download these processed datasets? :)

**Comment by clearloveclearlove** [comment]
> Thanks for your suggestion. We have updated the toxic datasets with the pre-processed ones.

Thank you for your reply, how can I download these processed datasets? :)

**Comment by lifan-yuan** [comment]
The bash scripts for downloading datasets have been updated, so you can access the datasets by running the scripts.
